source 'https://rubygems.org'

ruby '3.0.2'
#ruby '2.7.2'

gem 'sinatra'
#gem 'thin'
gem 'puma'
# gem 'nokogiri', require: false
# gem 'rack-mini-profiler', require: false
# gem 'stackprof', require: false
# gem 'puma-metrics', require: false
